### ISSUE TITLE
Pong Data

### ISSUE THREAD

**Issue by slerman12** [mjacar/pytorch-nec#7]
Hi, I'd like to create a graph comparing the performance of NES on Pong to another algorithm. Would you be able to provide me with a copy of the dataset that produced the graph in the Readme? If this is possible, I would greatly appreciate it.

**Comment by mjacar** [comment]
I was sure that that data was gone, but looking back I was actually able to find it. You're slerman@ur.rochester.edu, correct?

**Comment by slerman12** [comment]
Yes—thanks so much!

**Comment by mjacar** [comment]
Email sent.
